---
chrony_service_name: chronyd
chrony_timezone: America/New_York
chrony_ntp_servers:
  - 192.168.34.15
  - 192.168.34.11
chrony_config_file: /etc/chrony.conf
chrony_config_logdir: /var/log/chrony
chrony_config_driftfile: /var/lib/chrony/drift
chrony_makestep_threshold: 1
chrony_makestep_limit: 10
chrony_allow:
  - 192.168.34.0/24
chrony_deny: []
...

