---
- name: Setup dns master
  hosts: dnsm
  remote_user: ansible
  become: yes
  tasks:

  - name: Install packages
    yum:
      name:
        - bind
        - bind-utils
      state: latest

  - name: start named
    service:
      name: named
      state: started

  - name: Configure dns master
    template:
      src: dnsm.j2
      dest: /etc/named.conf

  - name: copying .flz file
    template:
      src: ziyotek3.flz.j2
      dest: /var/named/ziyotek3.flz

  - name: copying .rlz file
    template:
      src: ziyotek3.rlz.j2
      dest: /var/named/ziyotek3.rlz

  - name: Start named
    service:
      name: named
      state: restarted


